language: go
go:
- 1.10.x
services:
- docker
addons:
  apt:
    packages:
      - docker-ce=18.03.1~ce-0~ubuntu
install:
- docker --version
env:
  global:
    - secure: D2knppvgVzJPcS5sBNmx2KHSvl/pejDFNuGe9PUIMKLovR7jXqtoCYuLCGPyYmBSdnnoueVyxBJ/8ORsgOzLCRQLeOlfR8L4LCMrWKR0n8wIxFLbXsXmjEa+5Q6xsJ2l0Duez6aI/DfPWbPPyPRFdF+qSJ3dagkUIC2izWYg9Fepa/nglxy8wLdVNaA1c8pSVRHEgzF4eCB6YLg0BdTEQ/VpN9UzaFWEBPkOv746ruGi8PBbf09TfFdssuTUcHQLNZqcevzwnJ+SMsgPdXf1HFATWd/wCjyosHFGRcMsp8lT/7CGTxb9pdQS0Tj3u3fKSa2HsSLShu/qk+W8H8IKCn+FzdtNmQqLplybwHnVsuLJUyG1hD7G4RCorokEDz3fx7KjSjlgVOj3KCG87f/Tr4Nf+zK+DogRkuYKKvT9Qp468vdGLBLVGCJkxIzlUYsd3kBc95xkhwrmCavvyH9bTstAfWLgkMJeBD7Tu4iu8viWMLW41O5+cfWbyZdoukL9VQfkcGhhMA6tmrx8sTTaWo0B7xzLn+ZqxkuskfZ1kFF0GufWV7twlyjkrwqrEckbQO8eVU32jR6Llv+bui8hvpbP6govi+RzI9eQYWoOgG9tK1DnHHsxt5E8f313O6xvQquDldMiO2rt75Mj2JnH5W1tqTN1i31WMx6rH+7yGHQ=
    - secure: f1KNGOhBeL0kM0s/NRHq/7jgN+kUonWYlTWELXi2gWNTdj2lvLjHMmPn9Rq0qsiwALzBpFSzFsMjPLdZGE/7/I2m4wqXOmOF6TEeMJToXsGBnl1fZNCW6ac3X53nXsDHTvB4Espz8h4tuCPJLCQYJmoyT5sBBv0bgGQtLiCxUlBckoOXunV2+0tQ4Z3eFcn7vdWNWtNWeK5RLrDvmbpt5bnvfzj1mBv80toxK/Do3VifXpP4VMpsvQAzikO9awANqqhNlgq/iWz/7TIeLkRTI021M7Tlz8I/D+5pX4U2A42eS9COolQhZW92tmC0bMLeC+8SUVFxKniJYs4J+hXmR1Wm/3IyrMYUSsFxSt1/9MtFOrJVe7iOIVeMXdq16O2XoSzhkFn8EoDc3F/vNuUjcclH5TVwKPcZIhzWqB9hHYojTI6fw2x6UeN/IFFMezlVmJaULJwefeznDj+ZSQq/wLpjJQUX/m1wYOtia5l38swXvwiydOZi0EtTtzlEQQT8k5dyCQbhVsQmIthZQ+RcY7PUrOzTJS1n+/oXjgpQBtplDfyHTfSmMDYcWKjyXDv0DORNHuRkcrNTrTj8Z8EcDwStHEDLGAxuEaMl807TnUm27VaJjtplg+sWICxLWvnPgL/HJ69iXBikHqXoiOX1uHJJ3jMAZyj/GjoAAfwy4aw=
script:
  - make build-linux
  - make build-windows
  - make build-osx
  - docker build -t sandwichcloud/terraform-provider-sandwich:latest .
  - if [ -n "$TRAVIS_TAG" ]; then  docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; fi
  - if [ -n "$TRAVIS_TAG" ]; then  docker tag sandwichcloud/terraform-provider-sandwich:latest "sandwichcloud/terraform-provider-sandwich:$TRAVIS_TAG"; fi
  - if [ -n "$TRAVIS_TAG" ]; then  docker push "sandwichcloud/terraform-provider-sandwich:$TRAVIS_TAG"; fi
  - if [ -n "$TRAVIS_TAG" ]; then  docker push sandwichcloud/terraform-provider-sandwich:latest; fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: PFDAM5ftjaG0YYUb4gUa4MHIKdv2de/NdWNGBATRuZL9KDcF+DmTOIgge1rWj35pgKCn3td2x24BdwpGwGLf9IhZueKpAXl+wgOReUhVrVEwVS1M54+LufgCV4KgKIoyZte2MkhsQDvmW3AJT+U/lmSU1FyrYdTqwYDV7mufXv1UVAFuYAbGuW+hlVIeSJ+Oy0fjGgS8UxJ7qUip9jSvWUCnCtKinQi/5Een4QgT5ofKOrifs0gGr6rpDMcCxG+BhyrB98mhrH5Ih20Xaunujtqj4wY0F50T2pNq8ONuP5CA3P2Wwk+Eg4qx7ebPCDEbMhtIQnAI9GRKGAD3gxVEVibFb6mvj56q8ouncUSHfCa6vouJf5Zi6p/v7B6Ma1YirggZK6XNfb2Q45QRhMhEvl2kOV+IbyW1AS/LMm+FVo3/p/8M7a1EJsPTPD7Z8wYxNhm8aQlzjuIYlGOkzUzfyDRJG2vVhmG+5brziiUbNkFqKB6ViH/GEe+Iv6JvsolefBTCi5ldwR3FozV6tawL6BfByNRAA/sPa8EwjmY9nGQeFKV1BC0G0U1Ysz/1i++R/qKJaq6BuvLf3LPKiRY0lGm4rAlZvfWILbFmrVgrJym6wPix5mY5tR4SbDtuO53AHdNFh3MbmgGOcJRZfqldYGRW5JytXXuyrR3K/6SEETw=
  file_glob: true
  file: bin/*
  on:
    tags: true
